export PATH="$HOME/bin:$PATH"
export EDITOR=nvim

# zsh-completions
autoload -Uz compinit && compinit

# fzf
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# ripgrep
export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"
