export PATH="$HOME/bin:$HOME/.local/bin:$PATH:$HOME/Library/Android/sdk/platform-tools"
export EDITOR=nvim

# https://wezfurlong.org/wezterm/faq.html#some-glyphs-look-messed-up-why-is-that
export LANG=en_US.UTF-8
# You don't strictly need this collation, but most technical people
# probably want C collation for sane results
export LC_COLLATE=C
setopt COMBINING_CHARS

# Fix colors in fd
export LS_COLORS=

# Don't add commands to history if they start with a space
setopt histignorespace

# zsh-completions
autoload -Uz compinit && compinit

# fzf
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# ripgrep
export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

# Android Studio / Tauri
export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
export ANDROID_HOME="$HOME/Library/Android/sdk"
export NDK_HOME="$ANDROID_HOME/ndk/$(ls -1 $ANDROID_HOME/ndk)"

# Useful aliases and functions
alias h="fc -liD"
alias ll="eza -al"
alias tree="eza --tree --ignore-glob node_modules"

local ZSHRC_DIR="$(dirname $(readlink $(print -P %N)))"
export FPATH="$ZSHRC_DIR/zsh:$FPATH"
autoload shrink_path

# Source other files if they exist
while read -r file
do
  [ -f "$file" ] && source "$file"
done <<< (
  "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
  "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"
)

# Mise
eval "$(mise activate zsh)"

function task() {
  local DIR=$(pwd)
  while [ ! -z "$DIR" ] && [ ! -f "$DIR/Taskfile" ]; do
    DIR="${DIR%\/*}"
  done
  $DIR/Taskfile $@
}

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform

# prompt
autoload -Uz colors && colors
autoload -Uz vcs_info

precmd_vcs_info() {
  vcs_info
}
precmd_functions+=( precmd_vcs_info )
zstyle ':vcs_info:git:*' formats '%F{yellow}%b '

setopt PROMPT_SUBST

NEWLINE=$'\n'
PROMPT="${NEWLINE}%F{244}%~ \$vcs_info_msg_0_%(?..%F{red}%? )%F{default}\$ "

# Function to set terminal title
function set_terminal_title() {
  if [[ -n "$1" ]]; then
    # When a process is running, show the command and the current directory
    print -Pn "\e]0;$(shrink_path -f) • $1\a"
  else
    # Default title showing only the current directory
    print -Pn "\e]0;$(shrink_path -f)\a"
  fi
}

# Pre-command hook to update the terminal title before each command
function preexec() {
  # Update the terminal title with the running command and the current directory
  set_terminal_title "$1"
}

precmd_functions+=( set_terminal_title )

# Call the function to set the initial title when the shell starts
set_terminal_title
